#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost/dissertationsystem?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true